# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackhubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='Supertrack',
            field=models.BooleanField(verbose_name=False),
        ),
        migrations.AlterField(
            model_name='track',
            name='color',
            field=models.CharField(default='0,0,220', max_length=500),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_type',
            field=models.CharField(default='bam', max_length=500),
        ),
    ]
