# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackhubs', '0003_track_trackhub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='TrackHub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackhubs.TrackHub'),
        ),
    ]
