# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackhubs', '0004_auto_20160721_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_type',
            field=models.CharField(max_length=20),
        ),
    ]
