# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciesName', models.CharField(max_length=50)),
                ('taxon', models.CharField(max_length=50)),
                ('auth', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('ucscName', models.CharField(max_length=50)),
                ('twoBitURI', models.CharField(max_length=500)),
                ('chainSet', models.CharField(max_length=500)),
                ('genes', models.CharField(max_length=500)),
                ('genesDescription', models.CharField(max_length=500)),
                ('genesURI', models.CharField(max_length=500)),
                ('stylesheetURI', models.CharField(default='www.biodalliance.org/stylesheets/gencode.xml', max_length=500)),
                ('trixURI', models.CharField(max_length=500)),
                ('collapseSuperGroups', models.BooleanField(verbose_name='True')),
            ],
        ),
    ]
